server:
  port: 8761

spring:
  application:
    name: discoveryservice
# MS? ??
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    ?? ???? ?? ?? discoveryService ? ?? ?? ?? ?
# ? ????? DiscoveryService ??? ??? ?? ??? ???? ?? ?